# Generated by Django 3.0.4 on 2020-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Ph_no', models.IntegerField(blank=True, null=True)),
                ('regards', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
